### ISSUE TITLE
Error when compiling release x64

### ISSUE THREAD

**Issue by YupCore** [nitvic793/dx12-engine-elixir#3]
Error C2102 for "&" a left-handed value is required
How can i fix that?

**Comment by nitvic793** [comment]
This error got introduced with a recent update. You can check out StackOverflow's solution here: https://stackoverflow.com/questions/65444256/error-c2102-requires-l-value-vs2019-how-to-fix

Another easy way to fix it is to just disable the conformance mode setting.  Change _Conformance Mode_ to "No" in the C/C++ -> Language project settings.
